data <- read.table(file="household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors=FALSE)
subdata <- subset(data, Date=="1/2/2007"|Date=="2/2/2007")
png("plot1.png", 480, 480)
hist(as.numeric(subdata$Global_active_power), col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()
