library(lubridate)
data <- read.table(file="household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors=FALSE)
subdata <- subset(data, Date=="1/2/2007"|Date=="2/2/2007")
png("plot3.png", 480, 480)
with(subdata, plot(dmy(Date)+hms(Time), Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering"))
with(subdata, lines(dmy(Date)+hms(Time), Sub_metering_2, col="red"))
with(subdata, lines(dmy(Date)+hms(Time), Sub_metering_3, col="blue"))
legend("topright", lty=c(1,1,1), col=c("black","red","blue"), legend=names(subdata)[7:9])
dev.off()